#include <imx/runtime.h>
#include "AppState.h"

// Declared in app_root.gen.cpp (generated by imxc)
namespace imx {
template <> void render_root<AppState>(imx::Runtime& runtime, AppState& state);
}

#ifdef _WIN32
#define EXPORT __declspec(dllexport)
#else
#define EXPORT __attribute__((visibility("default")))
#endif

extern "C" EXPORT void imx_render(imx::Runtime& runtime, AppState& state) {
    imx::render_root(runtime, state);
}
