#include <imx/runtime.h>
#include <imgui.h>
#include "AppState.h"

// Declared in app_root.gen.cpp (generated by imxc)
namespace imx {
template <> void render_root<AppState>(imx::Runtime& runtime, AppState& state);
}

#ifdef _WIN32
#define EXPORT __declspec(dllexport)
#else
#define EXPORT __attribute__((visibility("default")))
#endif

// ImGuiContext* must be passed from host — DLL has its own static ImGui globals
extern "C" EXPORT void imx_render(imx::Runtime& runtime, AppState& state, ImGuiContext* ctx) {
    ImGui::SetCurrentContext(ctx);
    imx::render_root(runtime, state);
}
